### ISSUE TITLE
Trouble requesting summoner name change (store)

### ISSUE THREAD

**Issue by yoimlive777** [HextechDocs/lcu-explorer#5]
I'm trying to change my account's summoner name through a request to the store.

I'm new to this, managed to pull my Account ID and token. I'm pretty lost now though, is anyone willing to help?

**Comment by yoimlive777** [comment]
Whoever helps me I'll send you like $10 for being helpful, I'm a quick learner, just want to get this done ^^ ty

**Comment by Hi-Ray** [comment]
Closed as this violates Riot Games' TOS
