### ISSUE TITLE
Api issue

### ISSUE THREAD

**Issue by Dobedoooo** [HextechDocs/lcu-explorer#7]
Why the browser can access but the program can not access the endpoint such as `/lol-match-history/v3/matchlist/account/{accountId}`:
In code: 
`{'errorCode': 'RESOURCE_NOT_FOUND', 'httpStatus': 404, 'message': 'Invalid function'}`
In chrome:
![uTools_1646450694495](https://user-images.githubusercontent.com/57029169/156865919-6dd337ba-a47f-4d47-b628-1fc11d6b5c25.png)
I'm confused.

**Comment by MingweiSamuel** [comment]
You are not allowed to use LCU for data the official Riot API already provides: https://developer.riotgames.com/apis#match-v5/GET_getMatchIdsByPUUID

Also I cannot reproduce the issue
```json
{"errorCode":"RPC_ERROR","httpStatus":404,"implementationDetails":{},"message":"not implemented: please use the puuid query"}
```
